services:
  db:
    build: .
    restart: unless-stopped
    container_name: db-access-service
    environment:
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
    volumes:
      - ./logs:/app/logs
      - ./db:/app/db
      - ./cert/server.p12:/app/cert/server.p12
    ports:
      - "8085:8085"
    networks:
      backend:
        ipv4_address: 192.168.2.4
    healthcheck:
      test: ["CMD", "nc", "-z", "192.168.2.4", "8085"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  backend:
    name: backend
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1